# Generated by Django 4.2.7 on 2024-02-12 11:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baskets', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='Basket',
        ),
        migrations.AlterModelTable(
            name='basket',
            table='basket',
        ),
    ]
