# Generated by Django 4.2.7 on 2024-02-12 12:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Booking',
        ),
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='BookingItem',
        ),
        migrations.AlterModelTable(
            name='booking',
            table='booking',
        ),
        migrations.AlterModelTable(
            name='bookingitem',
            table='booking_item',
        ),
    ]
