# Generated by Django 4.2.7 on 2024-02-12 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_rename_order_booking_rename_orderitem_bookingitem_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingitem',
            old_name='order',
            new_name='booking',
        ),
    ]
